<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 26 Jul 2013 21:53:47 +0000 by Chiller
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'publicArticleCommenting' => "Used for the JSON data returned for commenting system.",
 ); 
